name: gulapedia
description: "Aplikasi pemantau asupan gula harian."
publish_to: 'none' 
version: 1.1.1+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  flutter_bloc: ^9.1.1

  user_repository:
    path: packages/user_repository

  journal_repository:
    path: packages/journal_repository

  food_repository:
    path: packages/food_repository
    
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  equatable: ^2.0.7
  go_router: ^17.0.0
  openfoodfacts: ^3.23.0
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  table_calendar: ^3.2.0
  firebase_ai: ^2.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/brands/
    - assets/icons/
    - assets/images/


  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/segoeui/segoeui_light.ttf
          weight: 200
        - asset: assets/fonts/segoeui/segoeui_semi_light.ttf
          weight: 300
        - asset: assets/fonts/segoeui/segoeui.ttf
          weight: 400 # Regular
        - asset: assets/fonts/segoeui/segoeui.ttf
          weight: 500
        - asset: assets/fonts/segoeui/segoeui_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/segoeui/segoeui_bold.ttf
          weight: 700
        - asset: assets/fonts/segoeui/segoeui_bold.ttf
          weight: 800
        - asset: assets/fonts/segoeui/segoeui_black.ttf
          weight: 900
        - asset: assets/fonts/segoeui/segoeui_light_italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/segoeui/segoeui_light_italic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/segoeui/segoeui_light_italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/segoeui/segoeui_italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/segoeui/segoeui_italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/segoeui/segoeui_semi_bold_italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/segoeui/segoeui_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/segoeui/segoeui_bold_italic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/segoeui/segoeui_black_italic.ttf
          weight: 900
          style: italic